import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { Preset } from '../presets';
import { compressImage } from './imageUtils';

const subjectCache: Record<string, string> = {}; // Cache for image subject descriptions

function getAi(apiKeyOverride?: string) {
  const apiKey = apiKeyOverride || process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('Gemini API key not found. Please add it in Settings.');
  }
  return new GoogleGenAI({ apiKey });
}

function base64ToGenerativePart(base64: string, mimeType: string) {
  return {
    inlineData: {
      data: base64.split(',')[1],
      mimeType
    },
  };
}

export async function generateVisual(
  prompt: string, 
  preset: Preset, 
  base64Image?: string, 
  mimeType?: string,
  activeTab?: string,
  strictMode?: boolean,
  apiKey?: string
): Promise<string> {
  const model = "gemini-2.5-flash-image";

  let fullPrompt = `${prompt}. ${preset.basePrompt}. Negative prompt: ${preset.negativePrompt}`;
  const contents: any = { parts: [{ text: fullPrompt }] };

  if (base64Image && mimeType) {
    const imagePart = base64ToGenerativePart(base64Image, mimeType);
    if (strictMode) {
      const subject = await describeImageSubject(base64Image, mimeType, apiKey);
      fullPrompt = `STRICTLY RECREATE this subject: ${subject}. ${prompt}. ${preset.basePrompt}`;
      contents.parts = [imagePart, { text: fullPrompt }];
    } else {
      contents.parts.unshift(imagePart);
    }
  }

  const ai = getAi(apiKey);
  
  const config: any = {};
  if (!base64Image) {
    config.imageConfig = {
      aspectRatio: preset.aspectRatio || '1:1',
    };
  }

  const response: GenerateContentResponse = await ai.models.generateContent({
    model,
    contents,
    config,
  });
  
  const imagePart = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
  if (imagePart && imagePart.inlineData) {
    const compressed = await compressImage(`data:${imagePart.inlineData.mimeType || 'image/jpeg'};base64,${imagePart.inlineData.data}`, 0.7);
    return compressed;
  }

  throw new Error("No image generated by Gemini.");
}

export async function describeImageSubject(base64Image: string, mimeType: string, apiKey?: string): Promise<string> {
  const cacheKey = base64Image.substring(0, 500); // Use a portion of the base64 as a key
  if (subjectCache[cacheKey]) {
    return subjectCache[cacheKey];
  }

  const model = "gemini-3-flash-preview";
  const imagePart = base64ToGenerativePart(base64Image, mimeType);
  const contents = { parts: [imagePart, { text: "Describe the main subject of this image in a concise phrase for an AI art prompt." }] };
  const ai = getAi(apiKey);
  const result = await ai.models.generateContent({ model, contents });
  const description = result.text?.trim() || "subject";
  subjectCache[cacheKey] = description; // Store in cache
  return description;
}

export async function analyzeImage(base64Image: string, mimeType: string, apiKey?: string): Promise<Omit<Preset, 'name'>> {
  const model = "gemini-3-flash-preview";
  const imagePart = base64ToGenerativePart(base64Image, mimeType);
  const prompt = `Analyze this image and generate an AI art prompt that captures its style. Focus on medium, texture, color, and composition. Output only the prompt itself.`;
  const contents = { parts: [imagePart, { text: prompt }] };
  const ai = getAi(apiKey);
  const result = await ai.models.generateContent({ model, contents });
  return {
    basePrompt: result.text?.trim() || "vector art",
    aspectRatio: '1:1',
    negativePrompt: 'blurry, noisy, watermark, text, signature',
  };
}
